import Head from "next/head";
import Image from "next/image";
import Hero from '@/components/Hero'; 


import styles from "@/styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head >
        <title>Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main className={`${styles.main} `}>
        <Hero
        title="Oh Give Me A Home"
        subtitle='where the muffalo roam'/>
        </main>
    </>
  );
}
